add_batchnorm:
- false
- false
- false
add_dropout:
- true
- true
- true
- true
add_pooling:
- false
- false
- false
channels:
- 8
- 16
- 32
- 64
conv_kwargs:
  padding: 1
  stride: 2
dropout:
- 0.5
- 0.5
- 0.5
- 0.5
input_channels: 1
input_dims: !!python/tuple
- 91
- 109
- 91
kernel_size:
- 3
- 3
- 3
n_classes: 5
n_hidden_layers: 3
pooling_kernel:
- 2
- 2
- 2
- 2
